### ISSUE TITLE
Suggestions ameliorations

### ISSUE THREAD

**Issue by webmasterproxy-media** [ATM-Consulting/dolibarr_module_missionorder#4]
Bonjour ATM

Je teste votre module en v12
Ca semble marcher
Par contre 
Je vois pas l interet obligatoire du champ "Groupe associé"
Pas de PDF

**Comment by c-orazio** [comment]
Bonjour,
je n'arrive pas à utiliser le module sous dolibarr 14.0.5. 
Voir le topic ici : https://www.dolibarr.fr/forum/t/ordre-de-mission/33373/5
Merci de votre aide
C.O.

**Comment by atm-john** [comment]
Hi this mod is abandoned
