### ISSUE TITLE
problem of right

### ISSUE THREAD

**Issue by cot-al** [ATM-Consulting/dolibarr_module_missionorder#6]
Please see problem validating mission orders: [https://www.dolibarr.fr/forum/t/ordre-de-mission/33373](https://www.dolibarr.fr/forum/t/ordre-de-mission/33373)

Bonjour,
En fait j’ai une erreur au moment ou l’on doit faire valider son ordre de mission : comme si il n’y avait pas de destinataire :
[php7:error] [pid 442448] [client 79.83.3.216:44984] PHP Fatal error: Uncaught Error: Class 'TRH_valideur_groupe' not found in /var/www/dolibarr/dolibarr-11.0.5/htdocs/custom/missionorder/class/missionorder.class.php:202\
Avez-vous une idée de comment résoudre le problème?
merci

**Comment by atm-maxime** [comment]
Bonjour,

Ce module dépend d'un autre module "Valideur" qui n'est pas public. D'autre part, ce module n'est pas maintenu de notre côté.
